<?php

/**
 * PluginMessageFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class PluginMessageFile extends BaseMessageFile
{
  public function save(Doctrine_Connection $conn = null)
  {
    $this->setFileNamePrefix();

    return parent::save($conn);
  }

  protected function setFileNamePrefix()
  {
    $prefix = 'ms_'.$this->getSendMessageData()->getId().'_';

    $file = $this->getFile();
    if ($file)
    {
      $file->setName($prefix.$file->getName());
    }
  }
}
